server:
  port: 9090
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/RegistrationDB
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop

  mail:
    host: smtp.gmail.com
    port: 587
    username: hevalcanaslan@gmail.com
    password: mfxv rqbt kqno puii
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true